# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            Ishmeet Grewal
tagline:          student. traveler. programmer
url:              http://ishmeetgrewal.com
paginate:         1
paginate_path:    "blog/page:num"
baseurl:          /
author:
  name:           Ishmeet Grewal
  url:            http://www.ishmeetgrewal.com
  email:          me@ishmeetgrewal.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ishg/ishg.github.io

pages_list:       {'Home':'/','Blog':'/blog','Archive':'/blog/archive','Impossible List':'/blog/impossible', 'Travels':'/blog/travels'}
travels: 		  {'Appalachia':'/appalachia', 'Italy':'/italy', 'Costa Rica':'/costa-rica'}