title:            Ishmeet Grewal
description:      student. traveler. programmer.
disqus_shortname: ishmeetgrewal
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://www.ishmeetgrewal.com

# Owner/author information
owner:
  name:           Ishmeet Grewal
  avatar:         avatar.jpg
  bio:            "I am a computer science student aspiring to be a software engineer. I travel the world and constantly search for opportunities to learn something new."
  email:          
  # Social networking links used in footer. Update and remove as you like.
  twitter:        ishmeetgrewal
  facebook:       ishmeet.grewal
  github:         ishg
  stackexchange:  
  linkedin:       ishmeetgrewal
  instagram:      ishmeetgrewal
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +IshmeetGrewal

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-45766261-2
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: rogue
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

travels: {'Appalachia':'/appalachia', 'Italy':'/italy', 'Costa Rica':'/costa-rica', 'Honduras':'/honduras'}
