---
title: Ishmeet Grewal
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: student. traveler. programmer.
baseurl: ''
url: http://www.ishmeetgrewal.com
google_analytics: UA-45766261-2
owner:
  name: Ishmeet Grewal
  avatar: avatar.jpg
  bio: I am a computer science student aspiring to be a software engineer. I travel
    the world and constantly search for opportunities to learn something new.
  email: 
  twitter: 
  facebook: ishmeet.grewal
  github: ishg
  linkedin: ishmeetgrewal
  instagram: ishmeetgrewal
  google_plus: 
  disqus_shortname: ishmeetgrewal
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
highlighter: rouge
paginate: 5
gems:
- jekyll-sitemap
- jekyll-paginate
paginate_path: "/blog/page:num/"
