# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ishmeet Grewal's Blog
tagline:          Student. Traveler. Programmer
url:              http://ishmeetgrewal.com/blog
paginate:         1
baseurl:          /
author:
  name:           Ishmeet Grewal
  url:            http://www.ishmeetgrewal.com
  email:          me@ishmeetgrewal.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ishg/ishg.github.io
