# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ishmeet Grewal
tagline:          student. traveler. programmer
url:              http://ishmeetgrewal.me
paginate:         2
baseurl:          /
author:
  name:           Ishmeet Grewal
  url:            http://www.ishmeetgrewal.me
  email:          me@ishmeetgrewal.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ishg/ishg.github.io

pages_list:       {'About':'/about','Blog':'/blog','Archive':'/archive','Impossible List':'/impossible'}
