baseURL = "http://ishmeetgrewal.com/"
languageCode = "en-us"
title = "Ishmeet Grewal"

theme = "hugo-theme-stack"
paginate = 5

disqusShortname = "ishmeetgrewal"            # Change it to your Disqus shortname before using
DefaultContentLanguage = "en"                   # Theme i18n support

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
    
[params]
    mainSections = ["post"]
    featuredImageField = "image"
    rssFullContent = true
    
    [params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006"
        
    [params.sidebar]
        emoji = ""
        avatar = "img/avatar.jpg"
        subtitle = "traveler. programmer. climber."
        
    [params.article]
        math = false
        [params.article.license]
            enabled = false 
            default = "Licensed under CC BY-NC-SA 4.0"
            
    [params.comments]
        enabled = true
        provider = "disqus"         # Available: disqus, utterances    
        [params.comments.utterances]
            repo = ""
            issueTerm = "pathname"
            label = ""             # Optional
            theme = "preferred-color-scheme"
            
    [params.widgets]
        enabled = ['category-cloud','tag-cloud', 'archives']
        [params.widgets.archives]
            limit = 5
            ### Archives page relative URL
            path = "archives"       
        [params.widgets.tagCloud]
            limit = 10
        [params.widgets.categoryCloud]
            limit = 10
            
    [params.opengraph]
        [params.opengraph.twitter]
            site = ""
            card = "summary_large_image"
            
    [params.defaultImage]
        [params.defaultImage.opengraph]
            enabled = false
            local = false
            src = ""
            
[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = -100
        pre = "home"
    [[menu.main]]
        identifier = "about"
        name = "About Me"
        url = "about"
        weight = -90
        pre = "user"
    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "archives"
        weight = -70
        pre = "archives"
    [[menu.main]]
        identifier = "photography"
        name = "Photography"
        url = "photography"
        weight = -60
        pre = "camera"
    [[menu.main]]
        identifier = "impossible"
        name = "Impossible List"
        url = "impossible"
        weight = -50
        pre = "list"

# Social Links Menu
    [[menu.social]]
        identifier = "github"
        url = "https://github.com/ishg"
        weight = -50
        pre = "github"
    [[menu.social]]
        identifier = "linkedin"
        url = "https://linkedin.com/in/ishmeetgrewal"
        weight = -50
        pre = "linkedin"
    [[menu.social]]
        identifier = "instagram"
        url = "https://instagram.com/ishmeetgrewal"
        weight = -50
        pre = "instagram"
    [[menu.social]]
        identifier = "twitter"
        url = "https://twitter.com/ishmeetgrewal"
        weight = -50
        pre = "twitter"

[related]
    includeNewer = true
    threshold = 60
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 200

[markup]
    [markup.highlight]
        noClasses = false
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true