---
title: Ishmeet Grewal
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: programmer. traveler. climber.
baseurl: ''
url: http://localhost:4000
google_analytics: UA-45766261-2
owner:
  name: Ishmeet Grewal
  avatar: avatar.jpg
  bio: I am a software engineer traveling the world, always looking for opportunities to learn something new.
  email: 
  twitter: 
  facebook: 
  github: ishg
  linkedin: ishmeetgrewal
  instagram: ishmeetgrewal
  google_plus: 
  disqus_shortname: ishmeetgrewal
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
highlighter: rouge
paginate: 5
gems:
- jekyll-sitemap
- jekyll-paginate
paginate_path: "/blog/page:num/"
